apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-service
  template:
    metadata:
      labels:
        app: public-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: public-service
        image: xvnpw/public-service:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: public-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 5000
  selector:
    app: public-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: protected-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: protected-service
  template:
    metadata:
      labels:
        app: protected-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: protected-service
        image: xvnpw/protected-service:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: protected-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 5000
  selector:
    app: protected-service
